name: Nightly build
on: push

jobs:
  build:
    name: Nightly
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - run: ./gradlew build
      - if: ${{ success() }}
        run: ./gradlew publish